# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Selfie Sensei' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Selfie Sensei
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  target 'Selfie SenseiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Selfie SenseiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
